package com.myspace.order;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Order implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "ORDER_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "ORDER_ID_GENERATOR", sequenceName = "ORDER_ID_SEQ")
	private java.lang.Long orderId;

	@org.kie.api.definition.type.Label(value = "Payment Type")
	private java.lang.String paymentType;

	@org.kie.api.definition.type.Label(value = "Amount")
	private int amount;

	@org.kie.api.definition.type.Label(value = "Discount")
	private int discount;

	public Order() {
	}

	public java.lang.Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(java.lang.Long orderId) {
		this.orderId = orderId;
	}

	public java.lang.String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(java.lang.String paymentType) {
		this.paymentType = paymentType;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public int getDiscount() {
		return this.discount;
	}

	public void setDiscount(int discount) {
		this.discount = discount;
	}

	public Order(java.lang.Long orderId, java.lang.String paymentType,
			int amount, int discount) {
		this.orderId = orderId;
		this.paymentType = paymentType;
		this.amount = amount;
		this.discount = discount;
	}

}